service: atlas
frameworkVersion: '2'

provider:
  name: aws
  stage: v1
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  graphql:
    handler: graphql.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  main:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline
  - serverless-plugin-typescript